import pytorch_lightning as pl
from torch.utils.data import DataLoader
import pandas as pd
import sys
import os

# Ensure src in path
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from src.data.dataset import MultimodalDataset
from src.data.preprocess import TextPreprocessor, ImagePreprocessor, MetadataPreprocessor
from src.models.fusion import MultimodalFusionModel
from src.training.lightning_module import FakeNewsLightningModule

def main():
    # Load the real dataset generated by prepare_dataset.py
    print("Loading prepared real dataset...")
    df = pd.read_csv("prepared_dataset.csv")
    
    # Clean any accidental missing text rows
    df = df.dropna(subset=['text', 'label'])
    
    # Initialize Preprocessors
    print("Initializing preprocessors...")
    text_prep = TextPreprocessor(max_length=32)
    img_prep = ImagePreprocessor(image_size=128)
    meta_prep = MetadataPreprocessor()
    
    # Fit metadata preprocessor
    meta_features = df[['author_credibility', 'domain_reputation']].values
    meta_prep.fit(meta_features)

    # Initialize Dataset
    dataset = MultimodalDataset(df, "data/images", text_prep, img_prep, meta_prep)
    # CPU Training Optimization: Lower batch size to prevent memory overload
    dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

    # Initialize Model
    print("Initializing model...")
    # Meta input dim = 2 (author_credibility, domain_reputation)
    model = MultimodalFusionModel(metadata_input_dim=2, text_dim=768, image_dim=768, num_classes=1)
    
    # --- CPU MEMORY FIX ---
    # Freeze the massive text and image models (DistilBERT and ResNet) 
    # so we only train the lightweight classification layers.
    # This reduces parameters from 84,500,000 down to a few thousand!
    for param in model.text_extractor.parameters():
        param.requires_grad = False
    for param in model.image_extractor.parameters():
        param.requires_grad = False
    
    # Initialize Lightning Module
    lightning_module = FakeNewsLightningModule(model, lr=1e-4)
    
    # Train
    print("Starting training...")
    trainer = pl.Trainer(max_epochs=2, accelerator="auto")
    trainer.fit(lightning_module, train_dataloaders=dataloader, val_dataloaders=dataloader)

if __name__ == "__main__":
    main()
